=== pkrayzy/HostlistCompiler/src/schemas/configuration.schema.json
{
  "$id": "https://adguarad.com/hostlist-compiler.configuration.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Hostlist compiler configuration",
  "description": "Configuration for the hostlist compiler",
  "type": "object",
  "properties": {
    "name": {
      "description": "Filter list name",
      "type": "string",
      "minLength": 1
    },
    "description": {
      "description": "Filter list description",
      "type": "string"
    },
    "homepage": {
      "description": "Filter list homepage",
      "type": "string"
    },
    "license": {
      "description": "Filter list license",
      "type": "string"
    },
    "version": {
      "description": "Filter version",
      "type": "string"
    },
    "sources": {
      "description": "An array of the filter list sources",
      "type": "array",
      "minItems": 1,
      "items": {
        "$ref": "#/definitions/source"
      }
    },
    "transformations": {
      "description": "A list of the transformations that will be applied",
      "type": "array",
      "allOf": [
        {
          "not": {
            "allOf": [
              {
                "contains": {
                  "const": "Validate"
                }
              },
              {
                "contains": {
                  "const": "ValidateAllowIp"
                }
              }
            ]
          }
        },
        {
          "not": {
            "allOf": [
              {
                "contains": {
                  "const": "Validate"
                }
              },
              {
                "contains": {
                  "const": "ValidateAllowPublicSuffix"
                }
              }
            ]
          }
        },
        {
          "not": {
            "allOf": [
              {
                "contains": {
                  "const": "ValidateAllowIp"
                }
              },
              {
                "contains": {
                  "const": "ValidateAllowPublicSuffix"
                }
              }
            ]
          }
        }
      ],
      "items": {
        "type": "string",
        "enum": [
          "RemoveComments",
          "RemoveModifiers",
          "Compress",
          "Validate",
          "ValidateAllowIp",
          "ValidateAllowPublicSuffix",
          "Deduplicate",
          "InvertAllow",
          "RemoveEmptyLines",
          "TrimLines",
          "InsertFinalNewLine",
          "ConvertToAscii"
        ]
      }
    },
    "exclusions": {
      "description": "A list of rules (or wildcards) to exclude from the source.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "exclusions_sources": {
      "description": "An array of exclusions sources.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "inclusions": {
      "description": "A list of wildcards to include from the source. All rules that don't match these wildcards won't be included.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "inclusions_sources": {
      "description": "A list of files with inclusions.",
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "name",
    "sources"
  ],
  "additionalProperties": false,
  "definitions": {
    "source": {
      "description": "A source for the filter list",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the source",
          "type": "string",
          "minLength": 1
        },
        "source": {
          "description": "Path to a file or a URL",
          "type": "string",
          "minLength": 1
        },
        "type": {
          "description": "Type of the source",
          "type": "string",
          "enum": [
            "adblock",
            "hosts"
          ]
        },
        "transformations": {
          "description": "A list of the transformations that will be applied",
          "type": "array",
          "allOf": [
            {
              "not": {
                "allOf": [
                  {
                    "contains": {
                      "const": "Validate"
                    }
                  },
                  {
                    "contains": {
                      "const": "ValidateAllowIp"
                    }
                  }
                ]
              }
            },
            {
              "not": {
                "allOf": [
                  {
                    "contains": {
                      "const": "Validate"
                    }
                  },
                  {
                    "contains": {
                      "const": "ValidateAllowPublicSuffix"
                    }
                  }
                ]
              }
            },
            {
              "not": {
                "allOf": [
                  {
                    "contains": {
                      "const": "ValidateAllowIp"
                    }
                  },
                  {
                    "contains": {
                      "const": "ValidateAllowPublicSuffix"
                    }
                  }
                ]
              }
            }
          ],
          "items": {
            "type": "string",
            "enum": [
              "RemoveComments",
              "RemoveModifiers",
              "Compress",
              "Validate",
              "ValidateAllowIp",
              "ValidateAllowPublicSuffix",
              "Deduplicate",
              "InvertAllow",
              "RemoveEmptyLines",
              "TrimLines",
              "InsertFinalNewLine",
              "ConvertToAscii"
            ]
          }
        },
        "exclusions": {
          "description": "A list of rules (or wildcards) to exclude from the source.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "exclusions_sources": {
          "description": "An array of exclusions sources.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "inclusions": {
          "description": "A list of wildcards to include from the source. All rules that don't match these wildcards won't be included.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "inclusions_sources": {
          "description": "A list of files with inclusions.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "source"
      ],
      "additionalProperties": false
    }
  }
}

=== pkrayzy/HostlistCompiler/examples/whitelist/configuration.json
{
  "name": "AdGuard Allowlist",
  "description": "Combination of allowlists for use with AdGuard DNS.",
  "homepage": "https://github.com/AdguardTeam/AdguardSDNSFilter",
  "license": "GPLv3",
  "sources": [
    {
      "name": "Hagezi Blocklist Referrals",
      "source": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/blocklist-referral-native.txt",
      "type": "adblock",
      "transformations": [
        "RemoveModifiers",
        "Compress",
        "Validate"
      ]
    },
    {
      "name": "AdGuard Allowlist",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/dns_whitelist.txt",
      "type": "adblock",
      "transformations": [
        "RemoveModifiers",
        "Compress",
        "Validate"
      ]
    },
    {
      "name": "Personal Allowlist",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/dns_exclusions.txt",
      "type": "adblock",
      "transformations": [
        "RemoveModifiers",
        "Compress",
        "Validate"
      ]
    }
  ],
  "transformations": [
    "Deduplicate",
    "RemoveComments",
    "Compress"
  ]
}

=== pkrayzy/HostlistCompiler/examples/HaGeZi/configuration.json
{
  "name": "HaGeZi's Pro mini DNS/Browser Blocklist",
  "description": "Size-optimised version for DNS/Browser adblockers, e.g. for devices with less RAM. This list only contains domains from the Pro full that have been found on Top 1/10M lists (Umbrella, Cloudflare, Tranco, Chrome, BuiltWith, Majestic, DomCop).",
  "homepage": "https://github.com/AdguardTeam/AdguardSDNSFilter",
  "license": "GPLv3",
  "sources": [
    {
      "name": "HaGeZi's Pro mini DNS/Browser Blocklist",
      "source": "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/adblock/pro.mini.txt",
      "type": "adblock",
      "transformations": ["RemoveModifiers", "Compress", "Validate"]
    },
    {
      "name": "Brave Filter",
      "source": "https://raw.githubusercontent.com/brave/adblock-lists/refs/heads/master/brave-lists/brave-ios-specific.txt",
      "type": "adblock",
      "transformations": ["RemoveModifiers", "Compress", "Validate"]
    },
    {
      "name": "EasyPrivacy Admiral",
      "source": "https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers_admiral.txt",
      "type": "adblock",
      "transformations": ["RemoveModifiers", "Compress", "Validate"]
    }
  ],
  "transformations": ["Deduplicate", "Compress"],
  "exclusions_sources": [
        "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/adblock/whitelist-referral-native.txt",
        "https://raw.githubusercontent.com/hagezi/dns-blocklists/refs/heads/main/adblock/whitelist-referral.txt",
        "https://raw.githubusercontent.com/pkrayzy/FiltersCompiler/master/filters/DNSexclusions.txt",
        "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/oisd_excludes.txt",
        "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/oisd_unresolved.txt",
        "https://raw.githubusercontent.com/pkrayzy/WarpWhitelist/main/lists/dynamic_whitelist.txt"
      ]
}

=== pkrayzy/HostlistCompiler/examples/sdn/configuration.json
{
  "name": "AdGuard Simplified Domain Names filter",
  "description": "Filter composed from several other filters (English filter, Social media filter, Spyware filter, Mobile ads filter, EasyList and EasyPrivacy) and simplified specifically to be better compatible with DNS-level ad blocking.",
  "homepage": "https://github.com/AdguardTeam/AdguardSDNSFilter",
  "license": "GPLv3",
  "sources": [
    {
      "name": "HaGeZi's Light",
      "source": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt",
      "type": "adblock"
    },
    {
      "name": "AdGuard DNS filter",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/dns_optimized.txt",
      "type": "adblock",
      "exclusions": [
        "||dotomi.com"
      ],
      "exclusions_sources": [
        "https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/Filters/exclusions.txt",
        "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/dns_whitelist.txt"
      ]
    },
    {
      "name": "EasyPrivacy Admiral",
      "source": "https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers_admiral.txt",
      "type": "adblock"
    }
  ],
  "exclusions_sources": [
    "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/blocklist-referral-native.txt",
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/dns_exclusions.txt"
  ],
  "transformations": [
    "Deduplicate",
    "Compress",
    "Validate",
    "RemoveComments"
  ]
}

=== pkrayzy/HostlistCompiler/examples/easylist/configuration.json
{
  "name": "EasyList Content Blocker",
  "description": "Compilation of EasyList Fliters, Excluding Domains Blocked by DNS",
  "homepage": "https://github.com/AdguardTeam/AdguardSDNSFilter",
  "license": "GPLv3",
  "sources": [
    {
      "name": "EasyList",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/easylist.txt",
      "type": "adblock",
      "exclusions_sources": [
        "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/cname.txt"
      ]
    },
    {
      "name": "uBlock",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/ublock.txt",
      "type": "adblock"
    }
  ],
  "exclusions_sources": [
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/filter.txt",
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/exclusions.txt"
  ],
  "transformations": [
    "Deduplicate"
  ]
}

=== pkrayzy/HostlistCompiler/examples/OISD/configuration.json
{
  "name": "OISD",
  "description": "Filter composed from several other filters (English filter, Social media filter, Spyware filter, Mobile ads filter, EasyList and EasyPrivacy) and simplified specifically to be better compatible with DNS-level ad blocking.",
  "homepage": "https://github.com/AdguardTeam/AdguardSDNSFilter",
  "license": "GPLv3",
  "sources": [
    {
      "name": "https://small.oisd.nl",
      "source": "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/pro.mini.txt",
      "type": "adblock",
      "transformations": ["RemoveModifiers", "Compress", "Validate"]
    },
    {
      "name": "https://small.oisd.nl",
      "source": "https://raw.githubusercontent.com/brave/adblock-lists/refs/heads/master/brave-lists/brave-ios-specific.txt",
      "type": "adblock",
      "transformations": ["RemoveModifiers", "Compress", "Validate"]
    },
    {
      "name": "EasyPrivacy Admiral",
      "source": "https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers_admiral.txt",
      "type": "adblock",
      "transformations": ["RemoveModifiers", "Compress", "Validate"]
    }
  ],
  "transformations": ["Deduplicate", "Compress"],
  "exclusions_sources": [
        "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral.txt",
        "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/whitelist-referral-native.txt",
        "https://raw.githubusercontent.com/nextdns/click-tracking-domains/main/domains",
        "https://raw.githubusercontent.com/pkrayzy/FiltersCompiler/master/filters/DNSexclusions.txt"
      ]
}

=== pkrayzy/HostlistCompiler/examples/adguard/configuration.json
{
  "name": "AdGuard Base filters (Optimized)",
  "description": "Compilation of AdGuard Base Filters, Excluding Domains Blocked by DNS",
  "homepage": "https://github.com/AdguardTeam/AdguardSDNSFilter",
  "license": "GPLv3",
  "sources": [
    {
      "name": "AdGuard Base filters",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/adguard.txt",
      "type": "adblock",
      "exclusions_sources": [
        "https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_ads.txt",
        "https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_clickthroughs.txt",
        "https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_microsites.txt",
        "https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_trackers.txt",
        "https://raw.githubusercontent.com/AdguardTeam/cname-trackers/master/data/combined_disguised_mail_trackers.txt"
      ]
    },
    {
      "name": "Scriptlets",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/scriptlets.txt",
      "type": "adblock"
    }
  ],
  "exclusions_sources": [
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/filter.txt",
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/exclusions.txt"
  ],
  "transformations": [
    "Deduplicate"
  ]
}

=== pkrayzy/HostlistCompiler/examples/quickfix/configuration.json
{
  "name": "Quick Fixes Filter",
  "description": "Filter to quickly resolve content filtering issues on popular websites without updating the extension",
  "homepage": "https://github.com/AdguardTeam/AdguardSDNSFilter",
  "license": "GPLv3",
  "sources": [
    {
      "name": "Krayzylist",
      "source": "https://raw.githubusercontent.com/pkrayzy/Krayzylist/main/Blocklist",
      "type": "adblock"
    },
    {
      "name": "Paywalls",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/paywalls.txt",
      "type": "adblock"
    },
    {
      "name": "Scriptlets",
      "source": "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/scriptlets.txt",
      "type": "adblock"
    }
  ],
  "exclusions_sources": [
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/filter.txt",
    "https://raw.githubusercontent.com/pkrayzy/HostlistCompiler/master/optimized/exclusions.txt"
  ],
  "transformations": [
    "Deduplicate"
  ]
}
